const listings = [
  {
    title: "Luxury Beach Villa",
    description:
      "Beautiful beachside villa with sunset views and private pool.",
    propertyType: "villa",
    pricePerNight: 7500,
    location: {
      city: "Goa",
      country: "India",
      address: "Candolim Beach Road",
    },
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    beds: 3,
    amenities: ["wifi", "pool", "kitchen", "parking", "air conditioning"],
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2"],
  },

  {
    title: "Modern City Apartment",
    description: "Stylish apartment in the heart of Mumbai.",
    propertyType: "apartment",
    pricePerNight: 4200,
    location: {
      city: "Mumbai",
      country: "India",
      address: "Bandra West",
    },
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    beds: 2,
    amenities: ["wifi", "kitchen", "washing machine", "air conditioning"],
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688"],
  },

  {
    title: "Cozy Hill Cottage",
    description: "Perfect mountain retreat with scenic views.",
    propertyType: "house",
    pricePerNight: 3500,
    location: {
      city: "Manali",
      country: "India",
      address: "Old Manali Road",
    },
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    beds: 2,
    amenities: ["wifi", "fireplace", "kitchen", "heating"],
    images: ["https://images.unsplash.com/photo-1505691723518-36a5ac3be353"],
  },

  {
    title: "Luxury Penthouse",
    description: "Top floor penthouse with skyline view.",
    propertyType: "apartment",
    pricePerNight: 9500,
    location: {
      city: "Bangalore",
      country: "India",
      address: "Indiranagar",
    },
    maxGuests: 8,
    bedrooms: 4,
    bathrooms: 3,
    beds: 4,
    amenities: ["wifi", "pool", "gym", "parking", "kitchen"],
    images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb"],
  },

  {
    title: "Lake View Cabin",
    description: "Quiet wooden cabin beside a peaceful lake.",
    propertyType: "house",
    pricePerNight: 3800,
    location: {
      city: "Nainital",
      country: "India",
      address: "Mall Road",
    },
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    beds: 2,
    amenities: ["wifi", "kitchen", "balcony", "parking"],
    images: ["https://images.unsplash.com/photo-1505692794403-35c66cbe24c6"],
  },

  {
    title: "Desert Luxury Camp",
    description: "Experience royal desert camping in Jaisalmer.",
    propertyType: "villa",
    pricePerNight: 5000,
    location: {
      city: "Jaisalmer",
      country: "India",
      address: "Sam Sand Dunes",
    },
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    beds: 1,
    amenities: ["breakfast", "parking", "air conditioning"],
    images: ["https://images.unsplash.com/photo-1501183638710-841dd1904471"],
  },

  {
    title: "Heritage Haveli Stay",
    description: "Traditional Rajasthani haveli with royal interiors.",
    propertyType: "villa",
    pricePerNight: 6200,
    location: {
      city: "Udaipur",
      country: "India",
      address: "Lake Pichola",
    },
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    beds: 3,
    amenities: ["wifi", "pool", "breakfast", "parking"],
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267"],
  },

  {
    title: "Minimalist Studio",
    description: "Perfect studio for solo travellers.",
    propertyType: "studio",
    pricePerNight: 2200,
    location: {
      city: "Pune",
      country: "India",
      address: "Koregaon Park",
    },
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    beds: 1,
    amenities: ["wifi", "kitchen", "air conditioning"],
    images: ["https://images.unsplash.com/photo-1502672023488-70e25813eb80"],
  },

  {
    title: "Luxury Farmhouse",
    description: "Spacious farmhouse with pool and garden.",
    propertyType: "house",
    pricePerNight: 8000,
    location: {
      city: "Ahmedabad",
      country: "India",
      address: "Sanand Road",
    },
    maxGuests: 10,
    bedrooms: 4,
    bathrooms: 3,
    beds: 5,
    amenities: ["wifi", "pool", "parking", "garden", "kitchen"],
    images: ["https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6"],
  },

  {
    title: "Cliffside Ocean Villa",
    description: "Luxury villa overlooking the ocean.",
    propertyType: "villa",
    pricePerNight: 8800,
    location: {
      city: "Varkala",
      country: "India",
      address: "Varkala Cliff",
    },
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    beds: 3,
    amenities: ["wifi", "pool", "balcony", "air conditioning"],
    images: ["https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd"],
  },
];
